apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      role: rabbitmq
  template:
    metadata:
      labels:
        role: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12.8-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "admin"        
        - name: RABBITMQ_DEFAULT_PASS
          value: "admin"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"          

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
  selector:
    role: rabbitmq